### PR TITLE
Cluster filter analytic

### PR DESCRIPTION
**Pull request by spficklin**
## Description
This PR adds a new analytic that filters a CCM/CMX matrix of clusters where there is not sufficient power to "trust" the correlation value.   It creates a new set of CCM/CMX matrices without the clusters that failed the power test.  The power test is a correlation power test (appropriate for Pearson's/Spearman) and is implemented identically to the `pwr.r.test` function in R (https://www.rdocumentation.org/packages/pwr/versions/1.2-2/topics/pwr.r.test).  

## Dependencies
This analytic requires two dependencies:
- StatsLib:  https://www.kthohr.com/statslib.html
- CGEM:  https://www.kthohr.com/gcem.html

Both are header-only libraries, so you only need to download them and put them where your compiler finds header files--no need to compile.  In my case I put them in `/usr/local/include`.

### Step 1
Create a network using your favorite data set.  In my case I used the Yeast data (with 188 samples)  we have been using with KINC development.  It is best if you have used at least 30 for the minimum cluster size when creating the network, but lower is even better for the test.

 Once the CCM/CMX files are ready you can run the following `corrpower` analytic:
```
mpirun -np 10 kinc run corrpower --emx Yeast.emx --ccm Yeast.ccm --cmx Yeast.cmx --ccmout Yeast.corrpower.ccm --cmxout Yeast.corrpower.cmx --pwr.alpha 0.001 --pwr.power 0.8
```
Note:  Change the number of processors (`-np` flag) to suit your machine).  The `pwr.alpha` and `pwr.power` arguments provide the allowable Type I error rate (alpha) and the expected power  (1 - Type II error (beta).   

### Step 2
Once it completes, you need to extract the network file from the original CCM/CMX files and the new filtered versions. Be sure to set the `--mincorr` argument to 0.5.  This will allow for low-quality 

```
kinc run extract --emx "Yeast.emx" --ccm "Yeast.ccm" --cmx "Yeast.cmx" --format "text" --output "Yeast.th0.5.coexpnet.txt" --mincorr 0.5 --maxcorr 1

kinc run extract --emx "Yeast.emx" --ccm "Yeast.corrpower.ccm" --cmx "Yeast.corrpower.cmx" --format "text" --output "Yeast.corrpower.th0.5.coexpnet.txt" --mincorr 0.5 --maxcorr 1
```

### Step 3
Now we need to make sure that low powered edges are removed.  We can use `awk` to look for edges that have  `abs(r) < 0.66` and 30 samples.  This is the cutoff threshold when alpha = 0.001, power = 0.8 and there are only 30 samples.  These edges should be present in the network file created from the original CCM/CMX files, but absent from the filtered network file.  The following commands can be used to find and count of low-powered edges with 30 samples in both files:
```
awk '{if($3 > -0.66 && $3 < 0.66 && $7 == 30) print $0}' Yeast.th0.5.coexpnet.txt | wc
awk '{if($3 > -0.66 && $3 < 0.66 && $7 == 30) print $0}' Yeast.corrpower.th0.5.coexpnet.txt | wc
```
The count for the first should have multiple, but the second should be zero.

### CODE REVIEW

**Comment by spficklin** [comment]
I should note. The reason this analytic creates new CCM/CMX files is because the thresholding is dynamic.  It is not a hard cut-off such as in RMT. 

And I would recommend that this filtering occur prior to RMT or the Power-Law threshold analytics to help clean out noise.

**Comment by bentsherman** [comment]
Awesome work! For my first pass, I've tried to clean up your PR to make it match KINC's code style and not make any extraneous changes. In the future please try to remove such stray changes before commiting them.

Before we merge this PR we'll need to update the installation docs and the Dockerfile. Of course it would be nice if we could remove the statslib dependency somehow but I suspect that this library will come in handy for the other thresholding analytics, as well as the KINC.R features that are coming. I was able to add these headers pretty easily so I will update the docs accordingly.

**Comment by bentsherman** [comment]
Actually @spficklin if you could update the documentation I will update the Dockerfile.

**Review by bentsherman — APPROVED** [review]

**Comment by spficklin** [comment]
Thanks @bentsherman for the initial review.  In regards to this:

> In the future please try to remove such stray changes before committing them.

Is there a code-style document I can follow?  I did my best to try and follow, but otherwise I don't know how to make it match in all cases.   

I will update the install docs.

**Comment by spficklin** [comment]
Okay, I've updated the documentation. I went a big hog wild with it.  I've also added a Makefile in the `docs` folder so that I can build the documents and look at them locally.

**Comment by spficklin** [comment]
@bentsherman I tagged several other folks for review because I wasn't sure who would have time to review. But if you are happy with the code please feel free to merge.  Given you know more about KINC code than anyone I think you're review is sufficient.

**Comment by JohnHadish** [comment]
I disagree with doing this analysis. I was doing some research for adding a power test to my t-test in KINC.R, and I found information talking about the purpose of a power analysis, and errors that people make in how they use them. Please see these References:  

https://web.ma.utexas.edu/users/mks/statmistakes/PowerMistakes.html  
https://homepage.divms.uiowa.edu/~rlenth/Power/2badHabits.pdf  

and the comments I made on my pull request for KINC.R: https://github.com/SystemsGenetics/KINC.R/pull/9

**Comment by spficklin** [comment]
Hi @JohnHadish Thanks for reviewing the PR.   I think what you are feeling uncomfortable about is the idea of "retrospective power" or "observed power" which tries to put a probability that you would obtain significant results if you repeated an experiment where all experimental methods, and population statistics were the same.  I agree, that type of approach is highly discouraged.

This analytic doesn't do "retrospective" but rather "posteriori" power analysis.   With posteriori, you give it the number of samples you plan to collect, and the effect size you expect to capture, and it will indicate the expected power for that experiment.   That's what this analytic is doing.  Any clusters that don't have enough samples to adequately support a given correlation value (effect size) are excluded.   Because we know that GMMs allow Pearson assumption to be met, we can therefore use this analytic to ensure that the Type I and Type II error rates are controlled in the network.  

If the fact that doing this after correlation analysis makes it seem "retrospective" then what may help clear that up is that we could easily have applied this check prior to correlation analysis and skipped correlation for any cluster if there weren't enough samples, but the end result is still the same.

**Review by JohnHadish — APPROVED** [review]

**Comment by bentsherman** [comment]
@spficklin Honestly your code style was fine, I end up fixing any style issues as I review the code anyway, so I'm not a stickler on this point. My only guideline is to try to match the code around you, which you did just fine.

If you look at my first "Cleanup" commit you'll see that there were a few one-line changes to unrelated files, probably just artifacts of when you were playing around with the code, which I reverted. These kinds of changes are easy to spot so just be aware of them when you commit things.

**Pull request merged**
